### ISSUE TITLE
Parenthesis in string in subexpression breaks template compiling

### ISSUE THREAD

**Issue by shabubu** [zordius/lightncandy#281]
The PHP Code:
-------------
# Doesn't work
```php
{{{sprintf
     (_ 'foo %sbar%s test (1 2 3).')
     '<span class="font-bold"><i>'
     '</i></span>'
}}}
```
# Works
```
{{{sprintf
     (_ 'foo %sbar%s test 1 2 3.')
     '<span class="font-bold"><i>'
     '</i></span>'
}}}
```

The Issue:
----------
While migrating my teams code from v0.22 to v1.2.0 a significant portion of our templates stopped compiling.  These templates all seem to have the same error that looks like the following if you used the code i posted above:

```
ERROR: Error in 'sprintf
        (_ \'foo %sbar%s test (1 2 3).\')
        \'<span class="font-bold"><i>\'
        \'</i></span>\'': expect ')' but the token ended!! in /code/vendor/zordius/lightncandy/src/LightnCandy.php:110
```

After a large portion of debugging and testing this appears to be an issue with compiling the template when a sub expression has a string argument that uses parenthesis.  It appears that LightnCandy attempts to interpret the content in the parenthesis as a sub expression.

The flags we have been using are 
```
LightnCandy::FLAG_ADVARNAME | LightnCandy::FLAG_HANDLEBARSJS | LightnCandy::FLAG_INSTANCE | LightnCandy::FLAG_ERROR_EXCEPTION | LightnCandy::FLAG_RUNTIMEPARTIAL;
```

I have tried other combinations of flags during debugging (before realizing what was actually breaking) to no avail.  FWIW I used the built in helper of `log` instead of `_` and the error still occurred just to make sure it that it was not an implementation of our helpers that would be causing this.

**Comment by shabubu** [comment]
This looks related to https://github.com/zordius/lightncandy/issues/274 which was closed recently, but this problem does appear to still exist

**Comment by zordius** [comment]
Thank you for reporting this! Will try to fix this later.

**Comment by zordius** [comment]
minimal code to reproduce the issue:
```php
require('./vendor/autoload.php');
use LightnCandy\LightnCandy;

// The Template:
$template = <<<VAREND
{{{debug (debug 'foo bar (moo).')}}}
VAREND;

$phpStr = LightnCandy::compile($template, array(
'flags' => LightnCandy::FLAG_HANDLEBARS | LightnCandy::FLAG_ERROR_EXCEPTION
));

echo "Generated PHP Code:\n$phpStr\n";
```

**Comment by zordius** [comment]
This should be fixed in current master and the new released version https://github.com/zordius/lightncandy/releases/tag/v1.2.1, please try again, thanks.

**Comment by shabubu** [comment]
@zordius Thank you so much, we will try it out asap!

**Comment by laurenhamel** [comment]
I'm using `v1.2.3` and can confirm that I recently encountered this same error yet again while building a custom helper with `FLAG_ADVARNAME` enabled. My specific use case looks similar to this: 
```php
{{test 'foo bar' (toRegex '^(foo|bar|baz)')}}
```

**Comment by laurenhamel** [comment]
To add onto my previous comment, it's worth noting that the error I receive is not exactly the same as that of the original poster's, but rather, a fatal error due to the template not compiling.

**Comment by tunnela** [comment]
This should be reopened. Parser still fails if a parenthesis inside a string is not preceded by a space character.

**Comment by theodorejb** [comment]
This is correctly fixed now in https://github.com/devtheorem/php-handlebars.
